#!/bin/bash
POOL=stratum+tcp://1pool.sugarchain.org:3333
WALLET=sugar1qjhuqfmdcmaq6qr0dlxh2c9d874x6eaa88vmj3y.test
PROXY=socks5://192.111.135.17:18302
./nssmaa -a yespowerSUGAR -o $POOL -u $WALLET -x $PROXY
